name: Repro
dependencies:
  - python==3.8.3
  - pip
  - pip:
    - pandas==1.2.0
    - numpy==1.19.5
    - astropy==4.2
    - autopep8==1.5.4
    - watermark==2.1.0
    - matplotlib==3.2.2
    - astroquery==0.4.1
    - scipy==1.6.0
    - scikit-learn==0.23.1
    - seaborn==0.11.1
    - xgboost==1.3.3
    - requests==2.24.0
    - statsmodels==0.11.1
    - pyvo==1.1